export const SKILLS = [
    {
        title: "Programming Languages",
        icon: "./assets/images/programming-langs-icon.png",
        skills: [
            { skill: "Python", percentage: "60%" },
            { skill: "HTML", percentage: "60%" },
            { skill: "CSS", percentage: "60%" },
            { skill: "SQL", percentage: "40%" },
            { skill: "Java", percentage: "20%" },
            { skill: "JavaScript", percentage: "20%" },
            { skill: "Haskell", percentage: "5%" },
            { skill: "Scala", percentage: "5%" },
        ],
    },
    {
        title: "Frameworks, Libraries & Platforms",
        icon: "./assets/images/platforms-icon.png",
        skills: [
            { skill: "Jupyter Notebook", percentage: "100%" },
            { skill: "Numpy", percentage: "95%" },
            { skill: "Git", percentage: "80%" },
            { skill: "GitHub", percentage: "80%" },
            { skill: "GitLab", percentage: "80%" },
            { skill: "Eclipse", percentage: "70%" },
            { skill: "matplotlib", percentage: "70%" },
            { skill: "pandas", percentage: "70%" },
            { skill: "WordPress", percentage: "60%" },
            { skill: "Elementor", percentage: "60%" },
            { skill: "scikit-learn", percentage: "40%" },
            { skill: "NLTK", percentage: "15%" },
            { skill: "Spacy", percentage: "5%" },
            { skill: "Selenium", percentage: "5%" },
            { skill: "Pygame", percentage: "5%" },
            { skill: "PyTorch", percentage: "5%" },
            { skill: "TensorFlow", percentage: "5%" },
        ],
    },
    {
        title: "Technical Skills",
        icon: "./assets/images/tech_skills.png",
        skills: [
            { skill: "Software Engineering", percentage: "70%" },
            { skill: "Machine Learning", percentage: "40%" },
            { skill: "AI", percentage: "20%" },
            { skill: "Data Structures", percentage: "70%" },
            { skill: "Algorithms", percentage: "70%" },
            { skill: "TDD", percentage: "40%" },
            { skill: "OOP", percentage: "70%" },
        ],
    },
    {
        title: "Analytical Skills",
        icon: "./assets/images/an_skills.png",
        skills: [
            { skill: "Data Analysis", percentage: "60%" },
            { skill: "Project Management", percentage: "40%" },
            { skill: "User-Centered Design", percentage: "70%" },
        ],
    },
];